dataset_name: aicity
devices: ['cuda:0']
train_split: ['training']
val_split: ['validation']
dataset: {
  # json_file: ./data/aicity/annotations/aicity_track3_v3.json,
  # json_file: ./data/aicity/annotations/track3_Rearview_A1-train_A1-val.json,
  # json_file: ./data/aicity/annotations/track3_only_Rearview_A1-train_A1-val.json,
  # json_file: ./data/aicity/annotations/track3_Rearview_A1-Alltraining.json,
  # json_file: ./data/aicity/annotations/track3_Rearview-Dashboard_A1-Alltraining.json,
  # json_file: ./data/aicity/annotations/track3_Rearview+Dashboard_A1-train_A1-val.json,
  json_file: /mnt/home/Temporal-Action-Localization-Relevant/aicity_track3/preprocess/track3_only_Rearview_A1-train_A2-val-nullAnno.json,
  feat_folder:  /mnt/home/Temporal-Action-Localization-Relevant/TAL_track3_self/features/ego,
  file_prefix: ~,
  file_ext: .npz,
  num_classes: 16,
  input_dim: 1024,
  feat_stride: 16,
  num_frames: 32,
  default_fps: 30,
  trunc_thresh: 0.3,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 2048,
  # max_seq_len: 1024,
  feats_concat: False,
}
model: {
  regression_range: [[0, 4], [2, 8], [4, 16], [8, 32], [16, 64], [32, 10000]],
  fpn_type: identity,
  n_head: 4,
  channel_att_sride: 2,
  embd_dim: 512,
  fpn_dim: 512,
  head_dim: 512,
  embd_kernel_size: 3,
  max_buffer_len_factor: 4.0,
  n_mha_win_size: 9,
  use_abs_pe: False,
  use_rel_pe: False,
}
opt: {
  # type: AdamW, # SGD or AdamW
  learning_rate: 0.001,
  epochs: 40,
  # epochs: 15,
  # epochs: 30,
  weight_decay: 0.05,
}
loader: {
  batch_size: 1,
  num_workers: 8,
}
train_cfg: {
  init_loss_norm: 250,
  # loss_weight: 0.5,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  # center_sample_radius: 2.5,
  # label_smoothing:  0.25,
}
test_cfg: {
  # pre_nms_topk: 800,
  # max_seg_num: 400,
  pre_nms_topk: 5000,
  max_seg_num: 2048,
  min_score: 0.001,
  nms_sigma : 0.25,
  multiclass_nms: True
  # ext_score_file: ./data/aicity/annotations/cuhk_val_simp_share.json
  # ext_score_file: ./data/aicity/features_unifv2_clip400+sthv2_SingleTrained_224_A1A2/
}
output_folder: ./ckpt_crop_Rear_hybrid/
